#!/usr/bin/env python3
"""
Build murltools.html: the whole tool as one self-contained page, no server.

The page keeps templates/index.html's markup and CSS exactly; only the parts that
called Flask are replaced by the inlined JavaScript in tools/all_in_one/. Enum names
and QR tables are read from the installed meshtastic and qrcode packages at build
time, so they track the dependency instead of being hand-maintained here.

    python tools/build_all_in_one.py

Re-run after changing templates/index.html, anything in tools/all_in_one/, or after
upgrading meshtastic.
"""

import json
import re
from pathlib import Path

from meshtastic.protobuf import config_pb2, mesh_pb2

ROOT = Path(__file__).resolve().parent.parent
JS_DIR = Path(__file__).resolve().parent / 'all_in_one'
TEMPLATE = ROOT / 'templates' / 'index.html'
OUTPUT = ROOT / 'murltools.html'

VENDOR_DIR = JS_DIR / 'vendor'

# Third-party, inlined verbatim. Both licences are GPLv3-compatible; qrcode.js carries
# its MIT notice in its own header, jsQR's Apache-2.0 text ships alongside it.
VENDOR_PARTS = ['qrcode.js', 'qrcode_UTF8.js', 'jsQR.js']

# Load order matters: tables and helpers before the code that uses them.
JS_PARTS = ['protobuf.js', 'meshtastic.js', 'backend.js']

ATTRIBUTION = """<!--
  murltools, built as a single self-contained page by tools/build_all_in_one.py.
  Do not edit this file: edit templates/index.html or tools/all_in_one/ and rebuild.

  Bundled third-party code:
    * QR Code Generator for JavaScript - Copyright (c) 2009 Kazuhiko Arase, MIT.
      http://www.d-project.com/  (full notice retained in the inlined source below)
    * jsQR - Copyright (c) 2016 Cosmo Wolfe, Apache License 2.0.
      https://github.com/cozmo/jsQR  (see tools/all_in_one/vendor/jsQR.LICENSE)

  'QR Code' is a registered trademark of DENSO WAVE INCORPORATED.
  Meshtastic is a registered trademark of Meshtastic LLC.
-->
"""


def enum_names(descriptor, field_name):
    field = descriptor.fields_by_name[field_name]
    return [value.name for value in field.enum_type.values]


def build_tables_js() -> str:
    """Emit the protobuf enum names read from the installed meshtastic package."""
    lora = config_pb2.Config.LoRaConfig.DESCRIPTOR
    user = mesh_pb2.User.DESCRIPTOR

    tables = {
        'ENUMS': {
            'modem_preset': enum_names(lora, 'modem_preset'),
            'region': enum_names(lora, 'region'),
            'hw_model': enum_names(user, 'hw_model'),
            'role': enum_names(user, 'role'),
        },
    }

    lines = ['// Generated by tools/build_all_in_one.py -- do not edit here.']
    for name, value in tables.items():
        lines.append(f'const {name} = {json.dumps(value, separators=(",", ":"))};')
    return '\n'.join(lines)


def main() -> None:
    html = TEMPLATE.read_text()

    js = []
    for part in VENDOR_PARTS:
        js.append(f'// ---- vendor/{part} ----')
        js.append((VENDOR_DIR / part).read_text())
    js.append(build_tables_js())
    for part in JS_PARTS:
        js.append(f'// ---- {part} ----')
        js.append((JS_DIR / part).read_text())
    bundle = '\n'.join(js)

    # Our bundle goes in ahead of the template's own script block, so the fetch
    # shim is installed before any page code runs.
    marker = '    <script>'
    if marker not in html:
        raise SystemExit('Could not find the template script block')
    html = html.replace(marker, f'    <script>\n{bundle}\n    </script>\n\n{marker}', 1)
    html = ATTRIBUTION + html

    OUTPUT.write_text(html)
    print(f'wrote {OUTPUT.relative_to(ROOT)} ({len(html):,} bytes)')


if __name__ == '__main__':
    main()
